file:
  dir : D:/spring/projects/ecommerce/S3/

spring:
  session:
    store-type: redis

  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
# show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie